# Generated by Django 5.2.6 on 2025-09-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sobrenome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(max_length=200)),
                ('matricula', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='alunos',
        ),
    ]
